/*
    TEST_B_MAP.H
    Generated by gb_map_converter v1.3.
*/

#ifndef __MAP_TEST_B_MAP_H__
#define __MAP_TEST_B_MAP_H__

#define TEST_B_MAP_WIDTH 20
#define TEST_B_MAP_HEIGHT 18

extern const void __bank_test_b_map_data;

extern const unsigned char test_b_map_data[];

#endif
