/*
    TEST_B_TILES.H
    Generated by gb_map_converter v1.3.
*/

#ifndef __MAP_TEST_B_TILES_H__
#define __MAP_TEST_B_TILES_H__

#define TEST_B_TILE_COUNT 37

#define TEST_B_PALETTE 0x1B

extern const void __bank_test_b_tile_data;

extern const unsigned char test_b_tile_data[];

#endif
