/*
    TEST_B_TILES.H
    Generated by gb_map_converter v1.1.
*/

#ifndef __MAP_TEST_B_TILES_H__
#define __MAP_TEST_B_TILES_H__

#define TEST_B_TILE_COUNT 37

extern const unsigned char TEST_B_TILE_DATA[];

#endif
