/*
    TEST_B_MAP.H
    Generated by gb_map_converter v1.2.
*/

#ifndef __MAP_TEST_B_MAP_H__
#define __MAP_TEST_B_MAP_H__

#define TEST_B_MAP_WIDTH 20
#define TEST_B_MAP_HEIGHT 18

extern const void __bank_TEST_B_MAP_DATA;

extern const unsigned char TEST_B_MAP_DATA[];

#endif
