/*
    TEST_A_TILES.H
    Generated by gb_map_converter v1.3.
*/

#ifndef __MAP_TEST_A_TILES_H__
#define __MAP_TEST_A_TILES_H__

#define TEST_A_TILE_COUNT 202

#define TEST_A_PALETTE 0x1B

extern const void __bank_test_a_tile_data;

extern const unsigned char test_a_tile_data[];

#endif
