/*
    TEST_A_MAP.H
    Generated by gb_map_converter v1.3.
*/

#ifndef __MAP_TEST_A_MAP_H__
#define __MAP_TEST_A_MAP_H__

#define TEST_A_MAP_WIDTH 20
#define TEST_A_MAP_HEIGHT 18

extern const void __bank_test_a_map_data;

extern const unsigned char test_a_map_data[];

#endif
