/*
    TEST_A_TILES.H
    Generated by gb_map_converter v1.1.
*/

#ifndef __MAP_TEST_A_TILES_H__
#define __MAP_TEST_A_TILES_H__

#define TEST_A_TILE_COUNT 202

extern const unsigned char TEST_A_TILE_DATA[];

#endif
