/*
    VILLAGE_OVERWORLD_MAP.H
    Generated by gb_map_converter v1.3.
    GitHub: https://github.com/borg100/gb_map_converter
*/

#ifndef __MAP_VILLAGE_OVERWORLD_MAP_H__
#define __MAP_VILLAGE_OVERWORLD_MAP_H__

#define VILLAGE_OVERWORLD_MAP_WIDTH 40
#define VILLAGE_OVERWORLD_MAP_HEIGHT 32

extern const void __bank_village_overworld_map_data;

extern const unsigned char village_overworld_map_data[];

#endif
