/*
    VILLAGE_HOUSE_5_TILES.H
    Generated by gb_map_converter v1.3.
    GitHub: https://github.com/borg100/gb_map_converter
*/

#ifndef __MAP_VILLAGE_HOUSE_5_TILES_H__
#define __MAP_VILLAGE_HOUSE_5_TILES_H__

#define VILLAGE_HOUSE_5_TILE_COUNT 50

#define VILLAGE_HOUSE_5_PALETTE 0x1B

extern const void __bank_village_house_5_tile_data;

extern const unsigned char village_house_5_tile_data[];

#endif
