/*
    VILLAGE_OVERWORLD_TILES.H
    Generated by gb_map_converter v1.3.
    GitHub: https://github.com/borg100/gb_map_converter
*/

#ifndef __MAP_VILLAGE_OVERWORLD_TILES_H__
#define __MAP_VILLAGE_OVERWORLD_TILES_H__

#define VILLAGE_OVERWORLD_TILE_COUNT 57

#define VILLAGE_OVERWORLD_PALETTE 0x1B

extern const void __bank_village_overworld_tile_data;

extern const unsigned char village_overworld_tile_data[];

#endif
