/*
    VILLAGE_HOUSE_1_MAP.H
    Generated by gb_map_converter v1.3.
    GitHub: https://github.com/borg100/gb_map_converter
*/

#ifndef __MAP_VILLAGE_HOUSE_1_MAP_H__
#define __MAP_VILLAGE_HOUSE_1_MAP_H__

#define VILLAGE_HOUSE_1_MAP_WIDTH 20
#define VILLAGE_HOUSE_1_MAP_HEIGHT 16

extern const void __bank_village_house_1_map_data;

extern const unsigned char village_house_1_map_data[];

#endif
